//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int CategoryId { get; set; }
        public int SectionId { get; set; }
        public System.Guid CategoryUUID { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public short CategoryOrder { get; set; }
        public bool Hidden { get; set; }
        public bool Conditional { get; set; }
        public string Picture { get; set; }
        public string ActionName { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
