//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientEmail
    {
        public int ClientEmailId { get; set; }
        public int ClientID { get; set; }
        public short EmailEventId { get; set; }
        public bool Success { get; set; }
        public string ErrorMessage { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual EmailEvent EmailEvent { get; set; }
    }
}
