//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDeliveryOption
    {
        public ClientDeliveryOption()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ClientId { get; set; }
        public string Description { get; set; }
        public decimal DeliveryAmount { get; set; }
        public byte OptionOrder { get; set; }
        public short ClientDeliveryOptionId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
