//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPaymentType
    {
        public short ClientPaymentTypeId { get; set; }
        public int ClientId { get; set; }
        public short PaymentTypeId { get; set; }
        public byte PaymentTypeOrder { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
