//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailEvent
    {
        public EmailEvent()
        {
            this.ClientEmails = new HashSet<ClientEmail>();
        }
    
        public short EmailEventId { get; set; }
        public string EventName { get; set; }
        public string DefaultTemplateName { get; set; }
    
        public virtual ICollection<ClientEmail> ClientEmails { get; set; }
    }
}
