//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public string Message { get; set; }
        public decimal TotalAmount { get; set; }
        public string CourierName { get; set; }
        public string TrackingNumber { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Paid { get; set; }
        public short ClientDeliveryOptionId { get; set; }
        public Nullable<short> ClientPaymentTypeId { get; set; }
        public System.Guid OrderUUID { get; set; }
        public short OrderStatusId { get; set; }
    
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual User User { get; set; }
        public virtual ClientDeliveryOption ClientDeliveryOption { get; set; }
        public virtual ClientPaymentType ClientPaymentType { get; set; }
    }
}
