//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public PaymentType()
        {
            this.ClientPaymentTypes = new HashSet<ClientPaymentType>();
            this.Orders = new HashSet<Order>();
        }
    
        public short PaymentTypeId { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public string Picture { get; set; }
    
        public virtual ICollection<ClientPaymentType> ClientPaymentTypes { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
