//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CartProducts = new HashSet<CartProduct>();
            this.ProductKeywords = new HashSet<ProductKeyword>();
            this.DiscountProducts = new HashSet<DiscountProduct>();
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
        public System.Guid ProductUUID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string AdminNotes { get; set; }
        public string Size { get; set; }
        public decimal Price { get; set; }
        public bool Hidden { get; set; }
        public bool Reserved { get; set; }
        public bool Sold { get; set; }
        public Nullable<System.DateTime> DateSold { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
        public string Picture3 { get; set; }
        public string Picture4 { get; set; }
        public string Picture5 { get; set; }
        public string PictureOther { get; set; }
        public string FacebookPostId { get; set; }
        public string TwitterPostId { get; set; }
        public string ProductShortUrl { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<CartProduct> CartProducts { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<ProductKeyword> ProductKeywords { get; set; }
        public virtual ICollection<DiscountProduct> DiscountProducts { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
    }
}
