//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int SectionId { get; set; }
        public int ClientId { get; set; }
        public System.Guid SectionUUID { get; set; }
        public string SectionName { get; set; }
        public string ControllerName { get; set; }
        public string SectionDescription { get; set; }
        public bool Hidden { get; set; }
        public string Picture { get; set; }
        public short SectionOrder { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual Client Client { get; set; }
    }
}
