//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public Setting()
        {
            this.ClientSettings = new HashSet<ClientSetting>();
        }
    
        public short SettingId { get; set; }
        public string SettingName { get; set; }
        public string SettingDescription { get; set; }
        public string RegexValidation { get; set; }
        public byte SettingTypeId { get; set; }
        public short SettingCategoryId { get; set; }
    
        public virtual ICollection<ClientSetting> ClientSettings { get; set; }
        public virtual SettingCategory SettingCategory { get; set; }
        public virtual SettingType SettingType { get; set; }
    }
}
