//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingCategory
    {
        public SettingCategory()
        {
            this.Settings = new HashSet<Setting>();
        }
    
        public short SettingCategoryId { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<Setting> Settings { get; set; }
    }
}
