//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThingFieldValue
    {
        public int ThingFieldValueId { get; set; }
        public int ThingFieldId { get; set; }
        public Nullable<int> IntValue { get; set; }
        public string StringValue { get; set; }
        public Nullable<bool> BoolValue { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual ThingField ThingField { get; set; }
    }
}
