//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThingField
    {
        public ThingField()
        {
            this.ThingFieldValues = new HashSet<ThingFieldValue>();
        }
    
        public int ThingFieldId { get; set; }
        public int ThingId { get; set; }
        public string FieldName { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual Thing Thing { get; set; }
        public virtual ICollection<ThingFieldValue> ThingFieldValues { get; set; }
    }
}
