//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThingAlert
    {
        public int ThingAlertId { get; set; }
        public string ThingName { get; set; }
        public string FieldName { get; set; }
        public short ThingAlertTypeId { get; set; }
        public short ThingAlertFrequencyId { get; set; }
        public int Criteria { get; set; }
        public string Description { get; set; }
        public string AlertSubject { get; set; }
        public string AlertBody { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> LastAlertSent { get; set; }
    
        public virtual ThingAlertFrequency ThingAlertFrequency { get; set; }
        public virtual ThingAlertType ThingAlertType { get; set; }
    }
}
