//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThingAlertType
    {
        public ThingAlertType()
        {
            this.ThingAlerts = new HashSet<ThingAlert>();
        }
    
        public short ThingAlertTypeId { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<ThingAlert> ThingAlerts { get; set; }
    }
}
