//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int UserId { get; set; }
        public int ClientId { get; set; }
        public System.Guid UserUUID { get; set; }
        public byte CredentialTypeId { get; set; }
        public string Identifier { get; set; }
        public byte[] Password { get; set; }
        public string PasswordSalt { get; set; }
        public string Email { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string FullName { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
