//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterApiDAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Users = new HashSet<User>();
            this.Sections = new HashSet<Section>();
            this.Discounts = new HashSet<Discount>();
        }
    
        public int ClientId { get; set; }
        public System.Guid ClientUUID { get; set; }
        public string ClientName { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<Discount> Discounts { get; set; }
    }
}
