//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMatterApiDAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public Discount()
        {
            this.DiscountProducts = new HashSet<DiscountProduct>();
        }
    
        public short DiscountId { get; set; }
        public short DiscountTypeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int DiscountAmount { get; set; }
        public int ClientId { get; set; }
    
        public virtual DiscountType DiscountType { get; set; }
        public virtual Client Client { get; set; }
        public virtual ICollection<DiscountProduct> DiscountProducts { get; set; }
    }
}
