-- Setting
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (1, 'BankName', '<p>The Bank name for EFT transactions</p>', 1, 1, null)
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (2, 'AccountName', 'The Account name for EFT transactions', 1, 1, null)
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (3, 'BranchName', 'The Branch Name for EFT transactions', 1, 1, null)
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (4, 'BranchNumber', 'The Branch Number for EFT transactions', 1, 1, '^[0-9]*$')
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (5, 'AccountNumber', 'The Account number for EFT transactions', 1, 1, '^[0-9]*$')
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (6, 'MapLongitude', 'The google map Longitude coordinates of the site physical office. e.g. 28.991066', 1, 2, '^-?([1-8]?[1-9]|[1-9]0)\.{1}\d{1,6}')
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (7, 'MapLatitude', 'The google map Latitude coordinates of the site physical office. e.g. -27.991066', 1, 2, '^-?([1-8]?[1-9]|[1-9]0)\.{1}\d{1,6}')
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (11, 'SEOKeywords', 'The keywords used for SEO. Comma delimited.', 1, 3, null)
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (12, 'SiteDescription', 'Your site description used for SEO. Usually your site name followed by a short description. E.g. MyCoolSite.co.za - Your favourite online store for cool goodies ', 1, 3, null)
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (13, 'SiteMetaDescription', 'Meta descriptions are commonly used on search engine result pages (SERPs) to display preview snippets for a given page. Should be unique for each page. E.g. online store selling cool goodies ', 1, 3, null)
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (14, 'SiteHomePageTitle', 'The title of your homepage. E.g. MyCoolSite Online Store', 1, 3, null)
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (20, 'EmailAddressSales', null, 1, 4, null)
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (21, 'EmailAddressInfo', null, 1, 4, null)
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (30, 'FacebookPageUrl', '', 1, 5, null)
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (31, 'TwitterUrl', '', 1, 4, null)
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (32, 'InstagramUrl', '', 1, 4, null)
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (33, 'PintrestUrl', '', 1, 4, null)
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (34, 'GooglePlusUrl', '', 1, 4, null)
insert into [Setting] ([SettingId], [SettingName], [SettingDescription], [SettingTypeId], [SettingCategoryId], [RegexValidation]) values (35, 'FacebookPostTemplate', null, 1, 5, null)
GO

